post_max_size = 5M
upload_max_filesize = 5M

session.save_handler = redis
session.save_path = "tcp://redis:6379"

; セッションを 1日（86400秒）にする
session.gc_maxlifetime = 86400      ; Redis に残る TTL（秒）
session.cookie_lifetime = 86400     ; ブラウザ側 Cookie の有効期限（秒）

; Cookie 安全属性（本番で HTTPS の場合は secure = 1 に）
session.cookie_httponly = 1
session.cookie_samesite = Lax
;session.cookie_secure = 1
